# KELOMPOK 10
RecSys Tugas Clo 2:
1. Audry Jesica Putri - 1301204119
2. Siti Uswah Hasanah - 1301204019
3. Surya Abadi - 1301204175
4. Ummu Husnul Khatimah - 1301204120


In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.metrics import mean_squared_error
from math import sqrt

In [ ]:
#mendefinisikan sample data
data = [['Alice', 'Item_1', 5], ['Alice', 'Item_2', 3], ['Alice', 'Item_3', 4],['Alice', 'Item_4', 4],
        ['User1', 'Item_1', 3], ['User1', 'Item_2', 1], ['User1', 'Item_3', 2], ['User1', 'Item_4', 3], ['User1', 'Item_5', 3],
        ['User2', 'Item_1', 4], ['User2', 'Item_2', 3], ['User2', 'Item_3', 4], ['User2', 'Item_4', 3], ['User2', 'Item_5', 5],
        ['User3', 'Item_1', 3], ['User3', 'Item_2', 3], ['User3', 'Item_3', 1], ['User3', 'Item_4', 5], ['User3', 'Item_5', 4],
        ['User4', 'Item_1', 1], ['User4', 'Item_2', 5], ['User4', 'Item_3', 5], ['User4', 'Item_4', 2], ['User4', 'Item_5', 1]]
rating = pd.DataFrame(data, columns=['User', 'Item', 'Rating'])

#merubah ke matrix rating
rating_matrix = rating.pivot_table(index='User', columns='Item', values='Rating')
rating_matrix = rating_matrix.fillna(0).T
#T untuk mentransposisi (menukar baris dan kolom) matriks rating.
print(rating_matrix)

User    Alice  User1  User2  User3  User4
Item                                     
Item_1    5.0    3.0    4.0    3.0    1.0
Item_2    3.0    1.0    3.0    3.0    5.0
Item_3    4.0    2.0    4.0    1.0    5.0
Item_4    4.0    3.0    3.0    5.0    2.0
Item_5    0.0    3.0    5.0    4.0    1.0


# Item-Based

In [ ]:
# Item-based Collaborative Filtering
def item_based_cf(rating_matrix, similarity_measure='pearson'):
    if similarity_measure == 'pearson':
        item_similarity = 1 - pairwise_distances(rating_matrix.T, metric='correlation')
    elif similarity_measure == 'cosine':
        item_similarity = cosine_similarity(rating_matrix.T)
    else:
        raise ValueError("Unsupported similarity measure")

    return item_similarity
def adjusted_cosine_similarity_ibcf(rating_matrix):
    # Hitung rata-rata per pengguna
    user_means = rating_matrix.mean(axis=1)

    # Adjust rating matrix dengan mengurangkan rata-rata per pengguna dari setiap nilai
    adjusted_ratings = rating_matrix.sub(user_means, axis=0)

    # Hitung similarity dengan cosine similarity
    similarity = 1 - pairwise_distances(adjusted_ratings, metric='cosine')

    return similarity

In [ ]:
item_similarity_pearson = item_based_cf(rating_matrix, similarity_measure='pearson')
item_similarity_cosine = item_based_cf(rating_matrix, similarity_measure='cosine')
adjusted_cosine_similarity_matrix_ibcf = adjusted_cosine_similarity_ibcf(rating_matrix)

In [ ]:
print("\nItem Similarity (Pearson):")
print(item_similarity_pearson)
print("\nItem Similarity (Cosine):")
print(item_similarity_cosine)
print("\nAdjusted Cosine Similarity for IBCF:")
print(adjusted_cosine_similarity_matrix_ibcf)


Item Similarity (Pearson):
[[ 1.         -0.05812382 -0.59030128 -0.28039985  0.20293852]
 [-0.05812382  1.          0.46770717  0.48995593 -0.9001488 ]
 [-0.59030128  0.46770717  1.         -0.16116459 -0.46656947]
 [-0.28039985  0.48995593 -0.16116459  1.         -0.6415029 ]
 [ 0.20293852 -0.9001488  -0.46656947 -0.6415029   1.        ]]

Item Similarity (Cosine):
[[1.         0.82686887 0.81016272 0.76277007 0.78954203]
 [0.82686887 1.         0.95938348 0.9356927  0.63781505]
 [0.81016272 0.95938348 1.         0.89442719 0.77151675]
 [0.76277007 0.9356927  0.89442719 1.         0.63831064]
 [0.78954203 0.63781505 0.77151675 0.63831064 1.        ]]

Adjusted Cosine Similarity for IBCF:
[[ 1.         -0.47673129 -0.12309149  0.53218116  0.0325128 ]
 [-0.47673129  1.          0.64549722 -0.31008684 -0.34099717]
 [-0.12309149  0.64549722  1.         -0.72057669 -0.484248  ]
 [ 0.53218116 -0.31008684 -0.72057669  1.          0.19032972]
 [ 0.0325128  -0.34099717 -0.484248    0.1903297

# User-Based

In [ ]:
# User-based Collaborative Filtering
def user_based_cf(rating_matrix, similarity_measure='pearson'):
    if similarity_measure == 'pearson':
        user_similarity = 1 - pairwise_distances(rating_matrix, metric='correlation')
    elif similarity_measure == 'cosine':
        user_similarity = cosine_similarity(rating_matrix)
    else:
        raise ValueError("Unsupported similarity measure")

    return user_similarity
# Adjusted Cosine Similarity
def adjusted_cosine_similarity_ubcf(rating_matrix):
    # Hitung rata-rata per item
    item_means = rating_matrix.mean(axis=0)

    # Adjust rating matrix dengan mengurangkan rata-rata per item dari setiap nilai
    adjusted_ratings = rating_matrix.sub(item_means, axis=1)

    # Hitung similarity dengan cosine similarity
    similarity = 1 - pairwise_distances(adjusted_ratings, metric='cosine')

    return similarity

In [ ]:
user_similarity_pearson = user_based_cf(rating_matrix, similarity_measure='pearson')
user_similarity_cosine = user_based_cf(rating_matrix, similarity_measure='cosine')
adjusted_cosine_similarity_matrix_ubcf = adjusted_cosine_similarity_ubcf(rating_matrix)

In [ ]:
print("\nUser Similarity (Pearson):")
print(user_similarity_pearson)
print("\nUser Similarity (Cosine):")
print(user_similarity_cosine)
print("\nAdjusted Cosine Similarity for UBCF:")
print(adjusted_cosine_similarity_matrix_ubcf)


User Similarity (Pearson):
[[ 1.         -0.47673129 -0.12309149  0.53218116  0.0325128 ]
 [-0.47673129  1.          0.64549722 -0.31008684 -0.34099717]
 [-0.12309149  0.64549722  1.         -0.72057669 -0.484248  ]
 [ 0.53218116 -0.31008684 -0.72057669  1.          0.19032972]
 [ 0.0325128  -0.34099717 -0.484248    0.19032972  1.        ]]

User Similarity (Cosine):
[[1.         0.78025959 0.81978229 0.94337007 0.7592566 ]
 [0.78025959 1.         0.94201969 0.84798442 0.67320142]
 [0.81978229 0.94201969 1.         0.78402509 0.62242512]
 [0.94337007 0.84798442 0.78402509 1.         0.81152606]
 [0.7592566  0.67320142 0.62242512 0.81152606 1.        ]]

Adjusted Cosine Similarity for UBCF:
[[ 1.         -0.73193406 -0.26722306  0.44009488 -0.19817039]
 [-0.73193406  1.          0.62061503 -0.38492243 -0.48256239]
 [-0.26722306  0.62061503  1.         -0.71912295 -0.63980987]
 [ 0.44009488 -0.38492243 -0.71912295  1.         -0.02986874]
 [-0.19817039 -0.48256239 -0.63980987 -0.0298687

# Prediksi Rating

In [ ]:
# Merubah ke matrix rating
rating_matrix = rating.pivot_table(index='User', columns='Item', values='Rating')
rating_matrix = rating_matrix.fillna(0)

In [ ]:
# Treshold similarity
threshold_similarity = 0.5

In [ ]:
# Membuat fungsi untuk menghitung prediksi rating
def predict_rating(user, item, rating_matrix, item_similarity_cosine, threshold_similarity):
    if user not in rating_matrix.index or item not in rating_matrix.columns:
        return "User or Item not found in the rating matrix"

    user_ratings = rating_matrix.loc[user]
    non_zero_ratings = user_ratings[user_ratings != 0]

    if item in non_zero_ratings.index:
        return "Rating for this item is already available"
    weighted_sum = 0
    total_similarity = 0

    for i in non_zero_ratings.index:
        similarity = item_similarity_cosine[rating_matrix.columns.get_loc(item)][rating_matrix.columns.get_loc(i)]
        if similarity > threshold_similarity:
            weighted_sum += similarity * non_zero_ratings[i]
            total_similarity += similarity

    if total_similarity == 0:
        return "Cannot make a prediction due to low similarity"

    predicted_rating = weighted_sum / total_similarity
    return predicted_rating

In [ ]:
# Predict Alice's rating for Item_5 using item-Based Cosine Similarity
user = 'Alice'
item = 'Item_5'
predicted_rating = predict_rating(user, item, rating_matrix, item_similarity_cosine, threshold_similarity)

if isinstance(predicted_rating, (int, float)):
    print(f'Predicted rating for {item} by {user}: {predicted_rating}')
else:
    print(predicted_rating)

Predicted rating for Item_5 by Alice: 4.053478012134915
